// ts
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { switchProfile } from "../../src/core/switch-service.js";
import { createAppPaths } from "../../src/storage/app-paths.js";
import { readJsonFile, writeJsonFile } from "../../src/storage/config-repo.js";
import type { PkgSwitchState } from "../../src/shared/types.js";

describe("switchProfile", () => {
  let homeDir: string | undefined;

  afterEach(async () => {
    if (homeDir) {
      await rm(homeDir, { force: true, recursive: true });
      homeDir = undefined;
    }
  });

  it("应写入托管 rc 文件、更新 state.json 并创建备份", async () => {
    homeDir = await mkdtemp(path.join(os.tmpdir(), "pkg-switch-"));
    const appPaths = createAppPaths(homeDir);

    await writeJsonFile(appPaths.configFile, {
      meta: {
        version: 1
      },
      defaults: {
        writeTargets: ["npm", "yarn"],
        backupBeforeWrite: true
      },
      common: {
        npm: {
          registry: "https://registry.npmmirror.com/",
          strictSsl: true
        },
        yarn: {
          nodeLinker: "node-modules"
        }
      },
      profiles: {
        "CJY-WORK": {
          npm: {
            registry: "https://nexus.example.com/repository/npm-group/",
            alwaysAuth: true,
            authToken: "plain-text-token"
          },
          scopes: {
            "@company": {
              registry: "https://nexus.example.com/repository/npm-group/"
            }
          }
        }
      }
    });
    await writeFile(path.join(homeDir, ".npmrc"), "registry=https://old.example.com/\n", "utf8");
    await writeFile(path.join(homeDir, ".yarnrc.yml"), "npmRegistryServer: https://old.example.com/\n", "utf8");

    const result = await switchProfile({ homeDir, profileName: "CJY-WORK", skipCacheClean: true });

    const npmrc = await readFile(path.join(homeDir, ".npmrc"), "utf8");
    const yarnrc = await readFile(path.join(homeDir, ".yarnrc.yml"), "utf8");
    const state = await readJsonFile<PkgSwitchState>(appPaths.stateFile);

    expect(result.status).toBe("success");
    expect(result.backupId).toMatch(/^backup-/);
    expect(npmrc).toContain("; generated by pkg-switch");
    expect(npmrc).toContain("registry=https://nexus.example.com/repository/npm-group/");
    expect(npmrc).toContain("_authToken=plain-text-token");
    expect(yarnrc).toContain("nodeLinker: node-modules");
    expect(yarnrc).toContain("npmRegistryServer: https://nexus.example.com/repository/npm-group/");
    expect(state.activeProfile).toBe("CJY-WORK");
    expect(state.lastBackupId).toBe(result.backupId);
    expect(state.lastWriteTargets).toEqual(["npm", "yarn"]);
    expect(state.lastSwitchStatus).toBe("success");

    await expect(readFile(path.join(appPaths.backupDir, result.backupId!, ".npmrc"), "utf8")).resolves.toContain(
      "registry=https://old.example.com/"
    );
    await expect(readFile(path.join(appPaths.backupDir, result.backupId!, ".yarnrc.yml"), "utf8")).resolves.toContain(
      "npmRegistryServer: https://old.example.com/"
    );
  });
});
