// ts
import type { ResolvedProfileConfig, ScopeConfig } from "../shared/types.js";

function appendBooleanLine(lines: string[], key: string, value: boolean | undefined): void {
  if (typeof value === "boolean") {
    lines.push(`${key}=${String(value)}`);
  }
}

function appendStringLine(lines: string[], key: string, value: string | undefined): void {
  if (value) {
    lines.push(`${key}=${value}`);
  }
}

function appendExtraConfigLines(lines: string[], extraConfig: Record<string, string | boolean> | undefined): void {
  for (const [key, value] of Object.entries(extraConfig ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`${key}=${String(value)}`);
  }
}

function appendScopeLines(lines: string[], scopeName: string, scope: ScopeConfig): void {
  appendStringLine(lines, `${scopeName}:registry`, scope.registry);
  appendBooleanLine(lines, `${scopeName}:always-auth`, scope.alwaysAuth);
  appendStringLine(lines, `${scopeName}:_authToken`, scope.authToken);
}

export function renderNpmrc(config: ResolvedProfileConfig): string {
  const lines = ["; generated by pkg-switch"];
  const npm = config.npm;

  if (npm) {
    appendStringLine(lines, "registry", npm.registry);
    appendStringLine(lines, "cache", npm.cache);
    appendBooleanLine(lines, "strict-ssl", npm.strictSsl);
    appendBooleanLine(lines, "always-auth", npm.alwaysAuth);
    appendStringLine(lines, "_authToken", npm.authToken);
    appendExtraConfigLines(lines, npm.extraConfig);
  }

  for (const [scopeName, scope] of Object.entries(config.scopes ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    // scope 在 merge 阶段已经处理 null，这里只负责稳定渲染。
    appendScopeLines(lines, scopeName, scope);
  }

  return `${lines.join("\n")}\n`;
}
