// ts
import { describe, expect, it } from "vitest";
import { renderNpmrc } from "../../src/managers/npmrc-renderer.js";

describe("renderNpmrc", () => {
  it("应输出托管头、npm 基础配置和 scope registry", () => {
    const output = renderNpmrc({
      npm: {
        registry: "https://nexus.example.com/repository/npm-group/",
        cache: "D:/DevCaches/npm-cache",
        strictSsl: false,
        alwaysAuth: true,
        authToken: "plain-text-token"
      },
      scopes: {
        "@company": {
          registry: "https://nexus.example.com/repository/npm-group/"
        }
      }
    });

    expect(output).toContain("; generated by pkg-switch");
    expect(output).toContain("registry=https://nexus.example.com/repository/npm-group/");
    expect(output).toContain("cache=D:/DevCaches/npm-cache");
    expect(output).toContain("strict-ssl=false");
    expect(output).toContain("always-auth=true");
    expect(output).toContain("_authToken=plain-text-token");
    expect(output).toContain("@company:registry=https://nexus.example.com/repository/npm-group/");
    expect(output).not.toContain("undefined");
    expect(output.endsWith("\n")).toBe(true);
  });

  it("应输出 npm extraConfig 中的自定义键", () => {
    const output = renderNpmrc({
      npm: {
        registry: "https://registry.npmmirror.com/",
        extraConfig: {
          "//nexus.example.com/repository/npm-public/:_auth": "\"base64-token\"",
          electron_mirror: "https://cdn.npmmirror.com/binaries/electron/",
          msvs_version: "2022"
        }
      }
    });

    expect(output).toContain("//nexus.example.com/repository/npm-public/:_auth=\"base64-token\"");
    expect(output).toContain("electron_mirror=https://cdn.npmmirror.com/binaries/electron/");
    expect(output).toContain("msvs_version=2022");
  });

  it("应把 pnpm.storeDir 渲染为 .npmrc 的 store-dir", () => {
    const output = renderNpmrc({
      npm: {
        registry: "https://registry.npmmirror.com/"
      },
      pnpm: {
        storeDir: "${HOME}/.local/share/pnpm/store"
      }
    });

    expect(output).toContain("store-dir=${HOME}/.local/share/pnpm/store");
  });
});
