// ts
import { describe, expect, it } from "vitest";
import { renderNpmrc } from "../../src/managers/npmrc-renderer.js";

describe("renderNpmrc", () => {
  it("应输出托管头、npm 基础配置和 scope registry", () => {
    const output = renderNpmrc({
      npm: {
        registry: "https://nexus.example.com/repository/npm-group/",
        cache: "D:/DevCaches/npm-cache",
        strictSsl: false,
        alwaysAuth: true,
        authToken: "plain-text-token"
      },
      scopes: {
        "@company": {
          registry: "https://nexus.example.com/repository/npm-group/"
        }
      }
    });

    expect(output).toContain("; generated by pkg-switch");
    expect(output).toContain("registry=https://nexus.example.com/repository/npm-group/");
    expect(output).toContain("cache=D:/DevCaches/npm-cache");
    expect(output).toContain("strict-ssl=false");
    expect(output).toContain("always-auth=true");
    expect(output).toContain("_authToken=plain-text-token");
    expect(output).toContain("@company:registry=https://nexus.example.com/repository/npm-group/");
    expect(output).not.toContain("undefined");
    expect(output.endsWith("\n")).toBe(true);
  });
});
